name: Build Workflow 1
on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build
