name: Event Info
on:
  push:
    branches:
      - workflow-setup
jobs:
  info:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: enforce-source-branch
      if: ${{ 'feature-1' == 'feature-1' }}
      run: |
        echo "::error:: Only PR from source branch 'feature-1' is accepted"
        exit 1
    -  run: |
        echo "Succeeded"