name: Event Info
on:
  pull_request:
    branches:
      - workflow-setup
jobs:
  info:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Info
      run: |
            echo PR from github.head_ref: ${{ github.head_ref }}
            echo PR from GITHUB_HEAD_REF: $GITHUB_HEAD_REF
            echo PR from 3. ${{ github.event.pull_request.head.ref }}
            echo Event info: ${{ toJSON(github.event) }}